#配置项目访问路径和端口
server:
  servlet:
    context-path: /demo
  port: 8080
  

#配置datasource连接池
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot-demo?zeroDateTimeBehavior=convertToNull&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
      username: root
      password: root
      #最大活跃数
      maxActive: 50
      #初始化数量
      initialSize : 5
      minIdle: 5
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计
      filters: stat
       
#扫描映射文件
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  
  
#配置分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  
  
#打印sql，在logback.xml中配置了，这里不用配置
#logging:
#  level:
#    com.kyle.demo.dao : debug